### ISSUE TITLE
Performance: changePage() searches the entire document for :focus elements

### ISSUE THREAD

**Issue by jblas** [jquery/jquery-mobile#1560]
In changePage() I see this:

$( window.document.activeElement || "" ).add( "input:focus, textarea:focus, select:focus" ).blur();

This will cause JQM to search the entire document every time we change pages just to release keyboard focus. Instead, we should probably be using a live("focus") handler and tracking the currently focused element so we don't have to crawl the document.

**Comment by gabrielschulhof** [comment]
1. Why do we need to kill focus? To get rid of the virtual keyboard?
2. How often do we end up using the selector instead of document.activeElement?
3. Does it really slow down our supported browsers significantly?

If we end up keeping the selector we need to change it to ```this.document.find( "input:focus, textarea:focus, select:focus" ).blur()```. We also need to change ```document.activeElement``` to ```this.document[ 0 ].activeElement```.

@arschmitz Could you please weigh in? [Here](https://github.com/jquery/jquery-mobile/blob/841db13f9ca68e622d4122954089cc4a560657c1/js/widgets/pagecontainer.js#L1038-L1053)'s the code in question.

**Comment by arschmitz** [comment]
We discussed this today it does not look like there is any case where this will actually happen. so lets go ahead and remove this, and clean it up.

**Comment by arschmitz** [comment]
This is fixed on master already
