### ISSUE TITLE
Create TransitionHandler object and expose it as an API

### ISSUE THREAD

**Issue by johnbender** [jquery/jquery-mobile#4022]
Recently we created two alternate transition handlers that encapsulate the sequential transition behavior and parallel transition behavior. Being that both are complex but relatively small this presents a really nice opportunity to refactor and provide an object api for advanced users to extend. 

https://gist.github.com/df62ba1902a7569e11fe

The above link is a 10 minute untested refactor example.

**Comment by gabrielschulhof** [comment]
I believe this is solved. You can now use transitions on their own: jsbin.com/zexic/1/ The styling is not exactly kosher, but the point is that it works. @arschmitz can we set up a checklist as to what else needs to be done to consider this feature production quality?

**Comment by gabrielschulhof** [comment]
I guess maybe a demo ... ?

**Comment by gabrielschulhof** [comment]
Desired outcomes:
- [ ] pagecontainer does not AMD-depend on transitions
    - [ ] Create pagecontainer extension that AMD-depends on transitions (maybe use ```transition()``` as the extension point)
- [ ] transitions do not AMD-depend on pagecontainer

**Comment by gabrielschulhof** [comment]
@arschmitz in order to achieve objective 2. I need to move [```$.mobile.focusPage```](https://github.com/jquery/jquery-mobile/blob/31cc90ddc8c051cb01db46e270478c12be9685bb/js/navigation.js#L100-L115) out of js/navigation.js. What do you think would be a good place for it? I was thinking about the page widget, but I don't like that the function searches for the page title, because that makes assumptions about the page's structure. This functionality was added way back in edaa43c479bb174191a5e9c419142d8637868961: "[...]Improves a11y experience."

I'm in the process of writing a PR for this issue, and for now I've moved the function into helpers. helpers is needed by both widgets/pagecontainer.js and transitions/transition.js - but, of course, so is widgets/page :)

Relevant issues:
#1342
#2965
