### ISSUE TITLE
Header and footer change their position after keyboard popup - iOS

### ISSUE THREAD

**Issue by mletynski** [jquery/jquery-mobile#4113]
When the content of page does not suit whole screen and we need to scroll, we have a problem with header and footer position.

Just open this link from safari ipad simulator:

http://jsfiddle.net/6ghtb/4/show/

Just click on input number 10  (last one which is visible before scrolling) and observe footer. It just jump and leave space between himself and the keyboard ...

When you scroll down and click most upper input, you have the same problem with header.

screenshot:
https://www.evernote.com/shard/s194/sh/c801a939-06a7-47cc-a3b8-70bb03af0ca1/30f7d6eb650566bfe6032f634b0381e5

**Comment by dpa99c** [comment]
I encountered this issue in a Cordova app using JQM 1.4.5 with iScroll 5.1.3 testing on iOS 8.3 

When the virtual keyboard is shown, scrolling the page using the iScroll widget causes the fixed footer to become unfixed and obscure the content.

The `target-densityDpi` viewport attribute didn't work for me, so I used a JS solution similar to @jenshoerburger to resolve the issue.

**Comment by Chener** [comment]
```
data-tap-toggle="false" data-hide-during-focus="false"
```

should do the trick.

**Comment by liangzhenghui** [comment]
@Chener  thank you very much.yours did the trick for me

**Comment by elsewhat** [comment]
Have this problem with a header. Implemented:
<meta name="viewport" content="width=device-width, height=device-height,initial-scale=1.0, maximum-scale=1.0, user-scalable=no,target-densityDpi=device-dpi"/>
and 
data-position="fixed" data-tap-toggle="false"

but unfortunately it's still not 100% solved. When I'm in one input field with keyboard active and click in another one, the header usually moves down ~100px

**Comment by arschmitz** [comment]
@elsewhat that is just how ios works there is not such thing as fixed position with the keyboard is open. any scrolling while the key board is open will cause any fixed position element to scroll with the page.

**Comment by elsewhat** [comment]
@arschmitz agree fully that this ought to be fixed in iOS. Instead of solving it at the root, we have to monkey around finding weird workaround

**Comment by arschmitz** [comment]
@elsewhat there is a workaround you need to force layout anytime there is a scroll which will cause them to update but this is very bad for performance

**Comment by lakinmohapatra** [comment]
$(window).resize(function(){
                if($(window).width() + $(window).height() != _originalSize){
                  console.log("keyboard show up");
                  $('#order-checkout-block').hide();
                }else{
                  console.log("keyboard closed");
                  $('#order-checkout-block').show();
                }
            });

**Comment by jtara** [comment]
lakinmohapatra, did you try that solution on iOS?

Unless something has changed in recent Mobile Safari versions, it does not change the size of *window* when the keyboard is shown.

But what does it solve? Not the subject of this Issue! Is it meant as a partial solution - e.g. how to determine if the keyboard is shown?

>Header and footer change their position after keyboard popup - iOS

Your solution for determining if keyboard shown would work for Android. But this is about iOS.

AFAIK, still, the only way to do that is the way *hadi77makkaw* showed for Cordova - using native code. I've also used native code in a different hybrid development environment (Rhomobile). I don't know of a way to do it for Mobile Safari itself, as then you can't use native code. So, seems only solvable if using a *UIWebView* or  *WKWebView* rather than system browser.

**Comment by pankajGODB** [comment]
Header and footer change their position after keyboard popup - iOS
1) Try adding cordova plugin add cordova-plugin-wkwebview-engine plugin for cordova project hope this will help because it helped in my page.
2) if above plugin doesnot help then remove cordova-plugin-wkwebview-engine and add  cordova plugin add cordova-plugin-crosswalk-webview. 

Issue will be resolve for header.
