### ISSUE TITLE
isCrossDomainPageLoad check is missing protocol values

### ISSUE THREAD

**Issue by zathrus-writer** [jquery/jquery-mobile#4845]
this line of isCrossDomainPageLoad check from jQuery Mobile 1.1.0 is missing a few values, preventing links to be automatically handled via the changePage() function:

isCrossDomainPageLoad = ( $.mobile.allowCrossDomainPages && documentUrl.protocol === "file:" && href.search( /^https?:/ ) != -1 ),

to fix this for BlackBerry and Windows Phone 7 at least, it should read:

isCrossDomainPageLoad = ( $.mobile.allowCrossDomainPages && (documentUrl.protocol === "file:" || documentUrl.protocol === "x-wmapp1:" || documentUrl.protocol === "local:") && href.search( /^https?:/ ) != -1 ),

**Comment by gabrielschulhof** [comment]
Unforunately, it's difficult to test on either Windows or Blackberry. I've gone through the pain of doing Cordova on Windows when fixing https://github.com/jquery/jquery-mobile/issues/6574, and I believe I've burned up my free Windows development time in the process ... and I can't get the Blackberry simulator running on Linux for the life of me, especially since VMware has gone all out to require licenses and stuff.

If anyone has a setup for doing Cordova on Windows and/or Blackberry, please create a jQuery Mobile project consisting of two documents which link to one another. Then click the link which leads to the other document. This should cause jQuery Mobile to attempt to load the other document via Ajax. If this fails on either platform, please comment here. We can then debug together. TIA!
