### ISSUE TITLE
hideDuringFocus doesn't work correctly on Chrome

### ISSUE THREAD

**Issue by benwwest** [jquery/jquery-mobile#5514]
I have created a simple JQuery Mobile prototype for an in house demo and have noticed a small issue with fixed footers.

The fixed footer seems to work fine on a desktop browser, however on mobile safari (possibly others) the fixed footer seems to move to the bottom of the entire page (i.e. of the screen) when a select box is opened.

I am using the data-tap-toggle="false" attribute on the footer to keep it visible even if the screen is tapped - it seems that when a select box is used it overrides this and still hides the footer/ sets it to the bottom of the page.

If you require an example please contact me privately and i'll share a link.

**Comment by gabrielschulhof** [comment]
I've tested hideDuringFocus on an Android 4.1.2 AVD and it doesn't work very well. The toolbars do not unfix when you open the select and they unfix, briefly re-fix, and then unfix again afterwards. So, even if we disregard the brief flash of them being fixed, the end state is wrong, because after the select closes, the toolbars should be fixed, rather than static.

**Comment by gabrielschulhof** [comment]
@jaspermdegroot I've found the reason why: Android 4.1.2 blurs the selectmenu button when it opens the native menu, so the fixedToolbar receives focusin and focusout in quick succession. Both focusin and focusout attach .animationComplete() handlers, which can interfere with each other. I've filed #7902 wherein I fix the problem. It's not a fix for this issue, but it's a good branch to work on issues of interaction between fixed toolbars and selectmenus.

**Comment by gabrielschulhof** [comment]
*sigh* Unfortunately, I think both #6028 and this issue stem from the fact that we have no way of knowing that the native selectmenu was closed.

**Comment by gabrielschulhof** [comment]
Just to illustrate:
1. Open http://jsbin.com/linine/1/ on Android 4.1.2
2. open the selectmenu
3. select a new item
At this point, the toolbar is hidden.

http://jsbin.com/linine/2/ refers to the modified version from the branch for #7902, and behaves correctly.

**Comment by gabrielschulhof** [comment]
Alright, I guess we can't fix this then.

**Comment by gabrielschulhof** [comment]
We have decided to remove the hideDuringFocus logic entirely, because we cannot implement it consistently. It is better to manually hide/show the fixed toolbars from your own application via the toolbar's ```hide()``` and ```show()``` methods, because the correct time to hide/show the toolbar must be determined per-application.
