### ISSUE TITLE
Focused mini text input within grid lacks right border 

### ISSUE THREAD

**Issue by mand1nga** [jquery/jquery-mobile#6795]
### Issue description
When using an input text field with attribute data-mini="true" within a 3-column grid, the right (blueish) border isn't quite visible

### jQuery Mobile and jQuery core version used
jquery-1.10.2
jquery.mobile-1.4.0-rc.1

### Test page 
http://jsbin.com/ofuhaw/1045/edit

### Steps to reproduce
Either see the test page with FF/Chrome latest or use the following code

<div class="ui-grid-a">
	<div class="ui-block-a">Cantidad</div>
	<div class="ui-block-b">
		<form id="pedidos-articulos-editar" data-rel="back">
			<input type="hidden" name="pedido_id" value="111" />
			<input type="hidden" name="articulo_id" value="15" />
			<input type="text" name="cantidad" id="cantidad" value="" data-mini="true" pattern="[0-9]+" />
		</form>
	</div>
</div>

### Expected outcome
Right border should be visible when input gets focus

### Actual outcome
Right border is not visible when input gets focus

![Image](https://dl.dropboxusercontent.com/u/6434162/jqm-6795.png)

### Platforms/browsers (including version) and devices tested
Firefox 25.0.1 and Chrome 31.0.1650.63 (latest)

### Other relevant information, e.g. using PhoneGap
Nothing else

**Comment by jaspermdegroot** [comment]
Mini size isn't relevant. This also happens with fullsize inputs.
The cause is that we set ```overflow: hidden``` for the grid container. We do that to give the container height which it otherwise won't have because all the children are floating.
We could look into using a clearfix instead of overflow hidden.

Reopening because the actual problem hasn't been fixed.

**Comment by gabrielschulhof** [comment]
I'm going to revert the fix because it causes #7990.

**Comment by gabrielschulhof** [comment]
@jaspermdegroot I'm trying various clearfix tricks with my limited CSS-fu. The source is http://stackoverflow.com/questions/211383/which-method-of-clearfix-is-best, though I haven't tried all the solutions.

http://jsbin.com/cinito/1/ (overflow: auto) (keeps clipping)
http://jsbin.com/cinito/2/ (:after trick) (seems to work)
http://jsbin.com/cinito/3/ (:before and :after) (seems to work)
http://jsbin.com/cinito/4/ (same as 3, but with display: block instead of display: table) (seems to work)

Do you approve of any of these?

**Comment by jaspermdegroot** [comment]
@gabrielschulhof 

We already use a clearfix in controlgroup.css so I suggest we use exactly the same trick. This is the same as your http://jsbin.com/cinito/3/. If I am not mistaken ```display: table;``` instead of ```display: block;``` is needed for IE8.

**Comment by gabrielschulhof** [comment]
OK. Can do.
