### ISSUE TITLE
Controlgroup float on chrome

### ISSUE THREAD

**Issue by zzart** [jquery/jquery-mobile#7793]
1. Controlgroup" data-type="horizontal" doesn't float ( left)  properly on Chrome 40 ( attached 2 screens one of firefox other chrome) 
Platforms: linux Chrome 40 , comparing with Firefox 35 
2. 
```html
<html class="ui-mobile"><head>
   <meta charset="utf-8">
   <meta name="viewport" content="width=device-width, initial-scale=1,maximum-scale=1, user-scalable=no">
    <link rel="stylesheet" href="http://code.jquery.com/mobile/1.4.4/jquery.mobile-1.4.4.min.css" />
<script src="http://code.jquery.com/jquery-1.11.1.min.js"></script>
<script src="http://code.jquery.com/mobile/1.4.4/jquery.mobile-1.4.4.min.js"></script>

</head>
<body>
 
<div data-role="page">
    <div data-role="header">
    
<div data-role="controlgroup" data-type="horizontal" data-mini="true">
    <a href="#" class="ui-btn ui-corner-all">No icon</a>
    <a href="#" class="ui-btn ui-corner-all ui-icon-delete ui-btn-icon-left">Left</a>
    <a href="#" class="ui-btn ui-corner-all ui-icon-delete ui-btn-icon-right">Right</a>


    
    <label for="select-h-6a">Select A</label>
    <select name="select-h-6a" id="select-h-6a">
        <option value="#">One</option>
        <option value="#">Two</option>
        <option value="#">Three</option>
    </select>
    <label for="select-h-6b">Select B</label>
    <select name="select-h-6b" id="select-h-6b">
        <option value="#">One</option>
        <option value="#">Two</option>
        <option value="#">Three</option>
    </select>
    <label for="select-h-6c">Select C</label>
    <select name="select-h-6c" id="select-h-6c">
        <option value="#">One</option>
        <option value="#">Two</option>
        <option value="#">Three</option>
    </select>

    
    <label for="select-h-6a">Select A</label>
    <select name="select-h-6a" id="select-h-6a">
        <option value="#">One</option>
        <option value="#">Two</option>
        <option value="#">Three</option>
    </select>
    <label for="select-h-6b">Select B</label>
    <select name="select-h-6b" id="select-h-6b">
        <option value="#">One</option>
        <option value="#">Two</option>
        <option value="#">Three</option>
    </select>
    <label for="select-h-6c">Select C</label>
    <select name="select-h-6c" id="select-h-6c">
        <option value="#">One</option>
        <option value="#">Two</option>
        <option value="#">Three</option>
    </select>

    
    <label for="select-h-6a">Select A</label>
    <select name="select-h-6a" id="select-h-6a">
        <option value="#">One</option>
        <option value="#">Two</option>
        <option value="#">Three</option>
    </select>
    <label for="select-h-6b">Select B</label>
    <select name="select-h-6b" id="select-h-6b">
        <option value="#">One</option>
        <option value="#">Two</option>
        <option value="#">Three</option>
    </select>
    <label for="select-h-6c">Select C</label>
    <select name="select-h-6c" id="select-h-6c">
        <option value="#">One</option>
        <option value="#">Two</option>
        <option value="#">Three</option>
    </select>

    
    <label for="select-h-6a">Select A</label>
    <select name="select-h-6a" id="select-h-6a">
        <option value="#">One</option>
        <option value="#">Two</option>
        <option value="#">Three</option>
    </select>
    <label for="select-h-6b">Select B</label>
    <select name="select-h-6b" id="select-h-6b">
        <option value="#">One</option>
        <option value="#">Two</option>
        <option value="#">Three</option>
    </select>
    <label for="select-h-6c">Select C</label>
    <select name="select-h-6c" id="select-h-6c">
        <option value="#">One</option>
        <option value="#">Two</option>
        <option value="#">Three</option>
    </select>

</div>
</div>
</div>

</body>
</html>
```

Screens

Firefox 35
![screen_1](https://cloud.githubusercontent.com/assets/432901/4701154/be30daf2-5855-11e4-9e79-b7250bbdd22d.png)
Chrome 40
![screen_2](https://cloud.githubusercontent.com/assets/432901/4701155/be360e46-5855-11e4-81f2-8a6e27d2b82c.png)

**Comment by gabrielschulhof** [comment]
@jaspermdegroot isn't the fact that it does not wrap at the left edge when it starts the next row a bug though?

**Comment by jaspermdegroot** [comment]
@gabrielschulhof - No it isn't. This is how floats work. Although it looks like all buttons in the row have the same height, the select ("One") is 3px taller. The button that doesn't fit in the first row bumps against that select when floating left.
If you use ```clear: left;``` (or ```both```) it will go all the way to the left, but we can't use that of course because we don't know what button has to go to a new row.

**Comment by gabrielschulhof** [comment]
@jaspermdegroot OK. I've created a very simple test case consisting of nothing but divs and one anchor which renders differently in FF than it does in Chrome:

http://jsbin.com/sifezo/1/

So, which one renders correctly? FF or Chrome?

Note that, in Chrome, if you set the .ui-btn padding to greather than, like, 0.9em, it starts to work the same way as FF. That's why I figured it was a Chrome bug - maybe a rounding error somewhere.

**Comment by gabrielschulhof** [comment]
I've simplified the test even further, removing the anchor and replacing it with a plain div.ui-btn:

http://jsbin.com/sifezo/2/

**Comment by gabrielschulhof** [comment]
If you change the .ui-btn padding from .7em to .8em, it all of a sudden works correctly.

**Comment by jaspermdegroot** [comment]
@gabrielschulhof - Using ```em``` values for top/bottom padding does give some unexpected results in Chrome and that is probably a rounding bug (has been reported).
I think the reason that the buttons in your test page don't have the same height is that for the first button ```inline-block``` is applied to an element that does have siblings, while in case of the other buttons it is applied to an element without siblings. Maybe Chrome's default browser style for ```inline-block``` elements is conditional or maybe there is a bug. I am not sure.
Comparing Firefox and Chrome isn't useful I think because their default style for ```inline-block``` can be different, without it being a bug.

**Comment by arschmitz** [comment]
This widget and css are all changed now so i'm going to close this.
