### ISSUE TITLE
Jquery mobile & Hammer js

### ISSUE THREAD

**Issue by jackyon** [jquery/jquery-mobile#7805]
Hi, currently i'm using jquery mobile for building an web app, every thing works great, but i found there is some bugs happened the swipe issues on Android devices. 

so I'm using the hammer js to solve those issues, jquery mobile 1.3.2 have no problem working with hammer js, but when I upgrade to version 1.4.4, the swipe event works weird, it is not smooth than before, most of time I need to swipe a lot of times then the swipe event will be trigger

hammer swipe usage: $(element).hammer().on("swipeleft", myFunction);
jquery mobile swipe usage: $(element).on('swipeleft',myFunction);

I think this issue happened because of the element binds multiple events, am I right?

plz advise any solution for this, I have been fighting with this issue couple of days.

thx!

**Comment by celron** [comment]
Greetings @arschmitz I believe that am running into this issue #7805  with jquery mobile 1.4.5.  I see that this is fixed, however I'm not sure what version this is fixed in (is it 1.4.5 or is it in the forthcoming 1.5?) or otherwise implement the fix on my own which I think is to pull out event.js or is it include it?

Thanks!
