### ISSUE TITLE
Demos: Cannot highlight, copy code shown in "View Source" popup using Chrome

### ISSUE THREAD

**Issue by gabrielschulhof** [jquery/jquery-mobile#7856]
This worked in 1.3.2.

**Comment by arschmitz** [comment]
Reopening based on #7907 as we may want to look at this more closely

**Comment by gabrielschulhof** [comment]
@arschmitz this is happening because we no longer set the tabindex on the popup container. It needs to be done per-application, because if we set it wholesale, we risk re-introducing the blue focus flash on Android.

**Comment by arschmitz** [comment]
I would say disabling all text selection in popups is a much more serious bug then a blue flash.

**Comment by suewonjp** [comment]
Hello.

Today, I copied some source code via that **"View Source"** button  from jQuery mobile demo site, and then I pasted the demo source code to my html file for some testing purpose.

Here two problems:

1. couldn't select text with press-down on Safari  (not a serious problem, I think...)
1. could select text by double-clicking, and could copy them, but...
  - ***The problem is some invisible non-ascii characters got sliped in the copied text. (This is serious in my opinion)***
  - This non-ascii characters caused some weird layout problem in my test with Phonegap on Android device, Chrome browser. 
  - This caused me a significant debugging time!!!  :-(

I don't know why those non-ascii characters are included there, but I think it's true other people like me may waste some time with this issue...

Can you raise up your priority to fix this issue? (The 2nd problem, especially...)

Thanks,

**Comment by apsdehal** [comment]
@suewonjp Can you specify the exact browser, its version and specific widget from where you copied the source?

**Comment by suewonjp** [comment]
First of all, the layout glitch looks like so:

![jqm-issue-7856](https://cloud.githubusercontent.com/assets/5332080/12661335/5ae47852-c65c-11e5-93fa-3319f5067f19.png)

I could reproduce the issue on either of Safari 9.0.3 on OS X Mavericks or Chrome 4.4 on Android. 

What I did was:

1. Go to http://demos.jquerymobile.com/1.4.5/navbar/ 
1. click the **View Source** button (under the 3 item navbar)
1. double click anywhere on the popup to select the entire text
1. copy the code
1. then, the whitespace portion of the copied code contains \xA0 which is non-ascii
    - of course, the characters are invisible. you need hex editor or something.
1. Removing the non-ascii has made the layout look normal.

Here's the test html file made of the code copied with the above procedure, thus containing a bunch of \xA0

[test.html.zip](https://github.com/jquery/jquery-mobile/files/108994/test.html.zip)
