### ISSUE TITLE
navbar counts "<script>" elements as navigation items

### ISSUE THREAD

**Issue by cchene** [jquery/jquery-mobile#7943]
A navigation bar si built from a `<ul>` containing `<li>` for each item.

From HTML 5 recommendation (http://www.w3.org/TR/html5/grouping-content.html#the-ul-element):
* `<ul>` can contain `<li>` and `<script>` elements,
* `<script>` is a "script supporting element" that is not to be rendered.

However, when a navbar's content mixes `<li>` and `<script>` elements, the display is incorrect. `<script>` elements are treated as `<li>` elements, i.e. they have a place reserved for them in the navbar.

See http://jsbin.com/varesivera/3/edit
Actual display is : a navbar with three buttons placed on top of each other and left-aligned.
Expected display is : a navbar with three buttons placed alongside horizontally.
Tested on Google Chrome 40.0.

Navbar building process should only take `<li>` elements into account and ignore any other child content.

**Comment by gabrielschulhof** [comment]
@arschmitz @jaspermdegroot it's [easy enough](https://github.com/gabrielschulhof/jquery-mobile/commit/40790312f1536b2498c788015d2f0ef35ca44b8e) to make the grid generator ignore script tags, but the problem is that, for the inset navbar, the right vertical border is added to the last button via ```:last-child``` which does not work if the last child is a script. So, we'd either need to use ```:last-of-type```, which is not supported before IE9, or:

1. Document that we do not support the last child being a script tag, or
2. Use ui-last-child, like we do with listview, and modify the CSS to not use ```:last-child```

What say you?

**Comment by jaspermdegroot** [comment]
I think this has been reported before. Let me try to find that ticket.

**Comment by jaspermdegroot** [comment]
Nevermind, can't find that ticket.

@cgack will this still be a problem with the reviewed navbar in 1.5?

I think we should be consistent across all widgets in how we deal with elements that should be ignored and making sure the right elements get corner styling. So I am in favor of "Use ui-last-child, like we do with listview, and modify the CSS to not use :last-child".

**Comment by cgack** [comment]
@jaspermdegroot the current status to the navbar review doesn't utilize the grid at all so it will behave appropriately: http://jsbin.com/qaguqo/1/edit?html,output
