### ISSUE TITLE
External panel not height 100%

### ISSUE THREAD

**Issue by cuongtallcat** [jquery/jquery-mobile#7983]
Hi

I run demo: http://demos.jquerymobile.com/1.4.2/panel-external/
Rotate horizontal, click button Overlay to show panel, panel not full height

![untitled](https://cloud.githubusercontent.com/assets/6701229/6506803/3da98bfe-c380-11e4-97e6-93553a9af858.png)

**Comment by Ruffio** [comment]
Which browser on which device/OS are you using?

**Comment by cuongtallcat** [comment]
I using Windows8, Chrome 40.0.2214.115 m, run with Device Mode: mobile

**Comment by jonas-db** [comment]
Try using 1.4.5 instead of 1.4.2?

**Comment by cuongtallcat** [comment]
The same bug on 1.4.5

**Comment by cuongtallcat** [comment]
If using position fixed, the content on external panel not show all,
I try set panel fixed and have scroller (scroll-y) , but when i scroll it, the main content is scroll too.
![untitled](https://cloud.githubusercontent.com/assets/6701229/6545272/7762109a-c5b1-11e4-8b95-9e7d4aa6fa83.png)

**Comment by gabrielschulhof** [comment]
I noticed this too. @arschmitz, @jaspermdegroot are panels supposed to be as tall as the document?

**Comment by gabrielschulhof** [comment]
OK, yes. Internal panels are the length of the page, but externals are not.

**Comment by jaspermdegroot** [comment]
They are supposed to be as tall as the page, just like "internal" panels, so it is a bug. You can see this issue on every device/browser.
With external panels ```body``` instead of ```ui-page``` is the containing block. Because we set ```height: 99.9%``` for ```body``` it has the height of the viewport, and so has the absolutely positioned panel which we make the same height as its container.
Looking into changing that to ```min-height``` has not much use since our pages are absolutely positioned as well so the ```body``` won't get the same height as the page.

@arschmitz - I think we talked about switching to ```position: relative;``` (and maybe set ```absolute``` during transitions?) for page at some point. If I remember correctly that had to do with an issue with external toolbars. Only if we make that change we can fix this with CSS. For now only with JS.
