### ISSUE TITLE
Fixed footer button

### ISSUE THREAD

**Issue by sfornengo** [jquery/jquery-mobile#8008]
Button in fixed footer are not inlined as in a fixed header:
http://jsbin.com/runuyezopa/1/edit?html,output

**Comment by gabrielschulhof** [comment]
Footers are handled differently from headers, so this is intentional. In fact, in 1.5.0, header buttons will not be altered in any way either, meaning that you will have to supply the classes to style them yourself.

Please see the last bullet point of http://jquerymobile.com/changelog/1.4.0/#toolbar

**Comment by gabrielschulhof** [comment]
See also:
https://github.com/jquery/jquery-mobile/issues/6331
https://github.com/jquery/jquery-mobile/issues/6137#issuecomment-20569793

**Comment by gabrielschulhof** [comment]
http://demos.jquerymobile.com/1.4.5/toolbar/#Buttonsintoolbars gives an example of buttons in a footer. Use a bit of custom CSS.
