### ISSUE TITLE
http://demos.jquerymobile.com/1.4.1/map-list-toggle/ list cannot slide on iPad latest

### ISSUE THREAD

**Issue by gmalagutti** [jquery/jquery-mobile#8065]
In the default demo there are a few items, but as you keep adding new items on the list using the 'show more' item at the bottom you find out that the list does not slide down to show unseen list items. It is limited to displaying only the top ones visible on screen.
This is verified on iPad, latest and latest OS, just updated. Probably iPhone will show the same unexpected behavior.
Tested with page
http://demos.jquerymobile.com/1.4.1/map-list-toggle/
not sure if the same demo is available on newer versions of jquery mobile

**Comment by kapilgarg1996** [comment]
@gmalagutti Its available in newer versions too..Try that one and see if the issue persists
http://demos.jquerymobile.com/1.4.5/map-list-toggle/

**Comment by gmalagutti** [comment]
I confirm that the bug is verified also at
http://demos.jquerymobile.com/1.4.5/map-list-toggle/

**Comment by kakul** [comment]
Issue reproduced in Mozilla Firefox responsive view:

![Scrollbars](https://lh5.googleusercontent.com/-EtgN0p4eTEg/VSk2H6JnqHI/AAAAAAAAA1s/qlq3hE9kC6M/w1043-h515-no/issue.png)

Possible reason: Conflicting behavior of overlapping scroll bars

Steps to reproduce:
1. Add more items using 'show more'. This creates another scroll bar for div map-page that is hidden behind the body scroll bar.
2. Reduce the width of div map-page to lower value so that the two overlapping scroll bars separate out and are visible.
