### ISSUE TITLE
[loader widget] problem in chrome

### ISSUE THREAD

**Issue by marti1125** [jquery/jquery-mobile#8124]
Hi!
$.mobile.loading('show',{
        	text: 'Loading...',
			textVisible: true,
			theme: 'a',
			html: ""
        });

I am trying to use this in chrome but it doesn't work and also this 

$(document).ajaxStart(function() {
    var loader = setInterval(function(){
        $.mobile.loading('show',{
        	text: 'Loading...',
			textVisible: true,
			theme: 'a',
			html: ""
        });
        clearInterval(loader);
    },1);

$( document ).ajaxStop(function() {
	
    var loader = setInterval(function(){
        $.mobile.loading('hide');
        clearInterval(loader);
    },1);
});
});
the problem is neve sync with loading ajax I only see the loader after finish...

**Comment by jaspermdegroot** [comment]
@marti1125 

Please provide a simple test page. See the [Contributing Guidelines](https://github.com/jquery/jquery-mobile/blob/master/CONTRIBUTING.md#issues) for our JS Bin template and instructions.
Thanks!

**Comment by kapilgarg1996** [comment]
@marti1125 Its working perfectly. Have a look here http://jsbin.com/dikula/1/edit?html,output
And i think the possible reason of its appearing at the end may be the multiple ajax requests you will be making at one time. Because the .ajaxStart() method is only called when only one ajax request is made and no other request is going on simultaneously.

**Comment by marti1125** [comment]
please close this issue
