### ISSUE TITLE
Overwrite data-transition globally

### ISSUE THREAD

**Issue by vaso123** [jquery/jquery-mobile#8130]
Hi!
I have a page, this is a responsive site. On desktop site, I do not want to use data-transitions, because the site hase a max-width, so transitions are looking ugly.

Anyway, because it is responsive, I do not want to remove the data-transition="..." from my links. All of my transitions are randomly, (wrote a PHP function, when render the page to pick one).

That could be good, if there will be a global option, where I can overwrite somehow this, to do not use data-transition, if client is not from mobile, in mobilinit. Sadly, there are only this:

$(document).bind('mobileinit', function () {
				if (!/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)) {
					$.mobile.defaultPageTransition = 'none';
				}
			});

great, but it is only set the default the none, but desktop page is using the links data-transitions attribute, not the default.

**Comment by Heidschnucke** [comment]
Try this:

$(document).on("pagecontainerbeforetransition", function (e, data) {
	if (!/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)) {
	  data.options.transition = "none";
	}
});

**Comment by arschmitz** [comment]
If your sight is responsive and you want transitions based on width you could do this with css. All our transitions are css based and so you could just negate them within a media query. 

If you want to use a JavaScript solution instead of testing the userAgent why are you not just checking
`$( window ).width()` to decide?

**Comment by jaspermdegroot** [comment]
@vaso123 - You can use ```$.mobile.maxTransitionWidth``` for this.

From the 1.2 docs:

Setting a max width for transitions
By default, transitions can be disabled (set to "none") when the window width is greater than a certain pixel width. This feature is useful because transitions can be distracting or perform poorly on larger screens. This value is configurable via the global option $.mobile.maxTransitionWidth, which defaults to false. The option accepts any number representing a pixel width or false value. If it's not false, the handler will use a "none" transition when the window is wider than the specified value.

The current docs lack this information. We are working on fixing this. Tickets: https://github.com/jquery/api.jquerymobile.com/issues/154 and https://github.com/jquery/api.jquerymobile.com/issues/146.

Closing this ticket because the requested feature is already available.
