### ISSUE TITLE
Update Build info in README

### ISSUE THREAD

**Issue by jaspermdegroot** [jquery/jquery-mobile#8339]
This information is outdated: https://github.com/jquery/jquery-mobile/tree/1.5-dev#buildcustomization Task "dist" doesn't exist anymore. Also have to check the other build tasks and the test tasks (https://github.com/jquery/jquery-mobile/tree/1.5-dev#testing).

**Comment by marti1125** [comment]
Hi! @jaspermdegroot how to I can help you with this?

**Comment by jaspermdegroot** [comment]
Hi @marti1125 

Thanks a lot for offering help!

In the "1.5-dev" branch the Grunt files have been split up in multiple files and tasks have been renamed.
The README.md file in that branch should be updated so it contains the right information about how to run tests, build demos, build framework JS and CSS files, etc..
Could you look into this and open a PR for it?

**Comment by marti1125** [comment]
@jaspermdegroot sure :D

**Comment by marti1125** [comment]
Hi @jaspermdegroot could you help with tests

- grunt test --suites=button,slider (buttons doesn't appear in console)
- grunt test --suites=button (Aborted due to warnings.)
- grunt test --type=integration --suites=!navigation (doesn't work....)
- I'm using grunt build:js insteand of grunt js because Error: Task "js" not found.

List of task
https://gist.github.com/marti1125/91ef6af42d76362d71c9

**Comment by jaspermdegroot** [comment]
@arschmitz - Can you help @marti1125 with this since you made the changes in the Grunt tasks? Thanks!

**Comment by arschmitz** [comment]
@marti1125 the current tasks are listed here https://github.com/jquery/jquery-mobile/blob/1.5-dev/build/tasks/alias.js 

there is no longer a button suite because this is now pulled in from jQuery UI and its tests live there.

If you need anything explained with the aliases we have set up just let me know

**Comment by marti1125** [comment]
@arschmitz Thanks
How to know what parameter can I pass into grunt task
- grunt test
- THEME=my-theme grunt css

@arschmitz @jaspermdegroot 
Is it okay if I change grunt build:js instead of grunt js?

https://github.com/jquery/jquery-mobile/blob/1.5-dev/build/tasks/alias.js#L24

**Comment by arschmitz** [comment]
@marti1125 the correct new task is `grunt build:js`

as far as parameters i don't think those have changed for equivalent tasks

**Comment by marti1125** [comment]
cool! I'm going to update the README

**Comment by marti1125** [comment]
@arschmitz 
about:  grunt test --type=integration --suites=!navigation
-bash: !navigation: event not found

**Comment by marti1125** [comment]
any update about this =)

**Comment by apsdehal** [comment]
@marti1125 This has been merged into 1.5-dev, closing accordingly.

**Comment by marti1125** [comment]
ok :)
