### ISSUE TITLE
Gauge Controls

### ISSUE THREAD

**Issue by jrahma** [jquery/jquery-mobile#8375]
I suggest you add gauge controls to jquery mobile

**Comment by arschmitz** [comment]
@jrahma thank you for this feature request this is something we would potentially consider adding though it would like be in jQuery UI and shared between the two libraries. Im going to close this since we don't keep feature requests open however feel free to continue to comment here and discuss details and implementation. IF you are interested in adding a proposal to add this to UI. Feel free to open an issue on the jQuery UI issue tracker / wiki as well
