### ISSUE TITLE
XSS issue in owasp and blackhat reports?

### ISSUE THREAD

**Issue by HIRANO-Satoshi** [jquery/jquery-mobile#8631]
Hi,

1. Issue description

jQuery Mobile was pointed out in the following reports that it had an XSS issue. Have it been fixed? or is it no problem?

https://www.blackhat.com/docs/us-17/thursday/us-17-Lekies-Dont-Trust-The-DOM-Bypassing-XSS-Mitigations-Via-Script-Gadgets.pdf

https://www.owasp.org/images/3/32/OWASP_BeNeLux-Day_2017_Bypassing_XSS_mitigations_via_script_gadgets_Sebastian_Lekies.pdf

_jQuery Mobile also has an HTML injection point, where the value of the "ID"
attribute is dynamically put inside an HTML comment. One can achieve
arbitrary code execution by simply closing the comment, and leave jQuery
manually execute the script.
Example: jQuery Mobile_

```
<div data-role=popup id='--><script>"use strict"
alert(1)</script>'></div>
```

Steps to reproduce ??
Expected outcome ?? 
Actual outcome ??

**Comment by ElliotNB** [comment]
This seems like a very low risk issue. If I'm understanding correctly, in order to exploit this vulnerability, you would have to have control of the ID attribute. Having control of the ID attribute implies either:

1. You have control of the front-end source itself.

2. The programmer built their jQuery Mobile widget such that the ID attribute is set using dynamic content from an external source.

If #1 is the scenario, then XSS is a moot point because you already have control of the source.

If #2 is the scenario, then the solution is to simply stop injecting dynamic content into the ID attributes.

**Comment by HIRANO-Satoshi** [comment]
Okay. Thanks!
